version: '3.6'
services:
  postgres:
    image: postgres:10
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /data/portfolio/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: fenglc/pgadmin4
    restart: "no"
    environment:
      DEFAULT_USER: admin
      DEFAULT_PASSWORD: admin
    volumes:
    - /data/portfolio/pgadmin:/var/lib/pgadmin
    ports:
    - "5050:5050"
