version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - /data/portfolio/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
  pgadmin:
    links:
    - postgres:postgres
    image: fenglc/pgadmin4
    restart: "unless-stopped"
    volumes:
    - /data/portfolio/pgadmin:/var/lib/pgadmin
    ports:
    - "5050:5050"
networks:
  postgres:
    driver: bridge
